### PR TITLE
limit number of tiles generated async due to spatialite limitation

### PR DESCRIPTION
**Pull request by arbakker**
Fixes https://github.com/t-rex-tileserver/t-rex/issues/234

The libspatialite max connections limitation is solved with libspatialite v4.4.0 (when compiled against GEOS 3.5.0), see
https://groups.google.com/g/spatialite-users/c/xrV7CA_GlwM . 

Commented the fix, so it can be removed at some later point in time.

### CODE REVIEW

**Comment by pka** [comment]
Thanks a lot for the investigation! The task queue size should be greater of equal than the number of available CPU cores. Instead of detecting the available cores, I've set the size to the hightest number of cores I could imagine. But when all these tasks use a DB connection, then we should definetively reduce them to the minimum. I will check whether we loose performance with setting the queue size to the number of cores.

**Comment by pka** [comment]
The build failure on Mac comes from an incompatibility of the `DummyDatasource` replacing the optional `GDALDatasource`. But I'll try to avoid the datasource check anyway.

**Comment by arbakker** [comment]
Aah, that makes sense. I already thought the task queue was quite big, but that explains. I suppose that the queue size should be limited to 64 for spatialite formats, if number of available cores > 64, in case the queue size is set to the number of cores.

**Comment by pka** [comment]
In a quick test, `num_cpus * 2` was faster than `num_cpus` and `128`. See  e1a67e9

**Pull request closed without merging**
