### PR TITLE
[WIP] Empty features

### PR DESCRIPTION
**Pull request by frodrigo**
- Omit layer without feature
- Tile without layer are still present but empty. I'm too newbie to deal with no tile in cache and/or 404. Nevertheless, a zero file size is still a valid PBF file.

### CODE REVIEW

**Comment by pka** [comment]
Still WIP, or shall I merge?

**Comment by frodrigo** [comment]
You can merge it as is. The 404 can be implemented later.

**Comment by pka** [comment]
Sorry, too late to merge the web server code. Can you try to rebase?

**Comment by pka** [comment]
Merged, thanks!

**Pull request closed without merging**
