### PR TITLE
Support postgres varchar[] data type

### PR DESCRIPTION
**Pull request by Blesss**
This PR is related to [#197](https://github.com/t-rex-tileserver/t-rex/issues/197)

### CODE REVIEW

**Comment by dmitrykinakh** [comment]
@pka - could you please review this and let us know if you approve this pull request?

**Comment by pka** [comment]
Thanks for your contribution!

**Comment by dmitrykinakh** [comment]
@pka - could you please let us know when the next release will happen?

**Comment by pka** [comment]
The next release is planned around mid-June.

**Comment by pka** [comment]
I think, you could close #197 with this commit?

**Comment by pka** [comment]
0.11.0 is released. Thanks for your contribution!

**Pull request merged**
