### PR TITLE
Fix for SSL to PostgreSQL and added sslmode=required explicit parameter to URL connection string

### PR DESCRIPTION
**Pull request by Daan-**
The TLS mode error message did not match with the error from the database, so TLS mode was never triggered in our situation (Azure PostgreSQL). Fixed by adding 'SSL connection is required' to the error messages.

Because of the backoff algorithm the connection with TLS took about 30 seconds more. (30 seconds of failing to setup a non TLS connection before trying to connect with TLS). By accepting the sslmode=require parameter in the connection string this 30 seconds is skipped and TLS is immediately tried. 

We have batch jobs with around 125.000 connections, so a 30 second extra wait for a PostgreSQL connection is quite substantial

### CODE REVIEW

**Comment by pka** [comment]
Hi @Daan-, I completely missed your PR, sorry!
Would you mind updating it to PG 0.17? I'm certainly interested. I wrote that complicated SSL connection handling because I wasn't able to connect to a hosted SSL-only PG like you. But either it's broken in the meantime, or Azure PG behaves different.

**Comment by lnicola** [comment]
To add, master is already on 0.17, but I'm not sure whether TLS still works (specifically whether it loads any certificates or not).

**Comment by Daan-** [comment]
Sure, next week I'm back in the (virtual) office so I will be able to make
the changes and test it.
Maybe Azure PG behaves different, the error message was not the same so the
reconnect never took place.

Op wo 23 sep. 2020 20:47 schreef Pirmin Kalberer <notifications@github.com>:

**Comment by Daan-** [comment]
Closed in favor of #217

**Pull request closed without merging**
